### ISSUE TITLE
Unable to logout from facebook

### ISSUE THREAD

**Issue by phantalab** [Innim/flutter_login_facebook#11]
Hi, 

The code 
`await widget.plugin.logOut();`
does not log the user out. (this code is taken from [link](https://pub.dev/packages/flutter_login_facebook#-example-tab-))

If I click on login button after clicking logout button, then a pop-up window appears for a second and I get the previous user automatically(i.e. it didn't logout the previous user).

I have noticed that if I log out from the Facebook app then the user in the app is also logged out.(without clicking logout button)

Please help me fix this bug, it is urgent!

**Summary:
The logout code given in the example doesn't actually log the user out because of which when we click on the login button the next time it automatically returns the previous logged in user.**

Thank you!

**Comment by greymag** [comment]
Hi!

I think maybe we talking about different logouts =)

Let's see. There is a 3 different "log in/log out":
1. **User logged in Facebook social network.** That's not our area of responsibility - we can't log out from network itself.
2. **User allow our Facebook app to log in with**. When user is log in for the first time - he allows our Facebook application to use his account for log in and gives some permissions. When he is log in next time - he doesn't need to allow anything, because he's already logged in to this Facebook app (in some login variants he may see "Continue" button to confirm log in, but without permissions, etc). Not sure if we can log out user from Facebook app (I think not), but we definitely  shouldn't, because user may have been logged in with our Facebook application in different places (mobile app and web, or simply on different devices), and logout in one place shouldn't force logout in all places. If user want to log out from all places - he can do it from his Facebook settings by revoke permissions from our Facebook app.
3. **User logged in via Facebook in our (mobile) application.** Define user session in specific app instance. That's what we control. Logout in this context just clear current access token, so user no longer logged in **this app instance**. But he is still logged in our Facebook app (so he can use it in different app instances) and he is still logged in Facebook itself. Thus if he click log in again - he will be logged in with minimum actions from his side.

So, plugin (and the [native SDK](https://github.com/facebook/facebook-ios-sdk/blob/412a86a785a3347e254910d7115a3df1aa822193/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.h#L167)) makes "logout" in the **3rd** context. To make sure that it's working you may:
1. Check `assessToken` after logout. It should be null (and it is).
2. Terminate app after logout and run it again. If we logged in - than session will be restored and we can see user information again, if it's not - user logged out from this app instance (and it's not).

**Summary:** Logout in plugin works as expected and designed by Facebook.

If I'm wrong or plugin doesn't works as described in some cases, please tell me about it. Have a nice day!
