### ISSUE TITLE
IOS logIn by app not working

### ISSUE THREAD

**Issue by godzeit** [Innim/flutter_login_facebook#21]
flutter: 1.17.5
flutter_facebook_login: ^3.0.0

Facing this kinda problem with facebook logIn on IOS. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48680083/88923685-890f7480-d28b-11ea-809d-8cc21b8a3452.gif)

**Comment by greymag** [comment]
Hey!

In the my app it's working well. 

![](https://d.pr/i/EQSv7y+)

I think it could be a conflict with some another plugin. Maybe it's plugin for handle open app by url - for example uni_links or something else. Could you check the plugin on new empty project to confirm or disprove an assumption?

**Comment by godzeit** [comment]
@greymag is it working okay on IOS 13? and did u also implimented vk and google in your example? Because I dont use uni_links. But I have:
google_sign_in: ^4.5.1
quick_actions: ^0.4.0+6
flutter_vk_sdk: ^0.1.0+3
flutter_login_facebook: ^0.2.0+1

**Comment by greymag** [comment]
> is it working okay on IOS 13?

Yes, it's captured from iOS 13.


> But I have:
> google_sign_in: ^4.5.1
> quick_actions: ^0.4.0+6
> flutter_vk_sdk: ^0.1.0+3

So, it's problem with flutter_vk_sdk =)
![](https://d.pr/i/niUvLJ+) 

It's should be
```swift
override func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
      return VKSdk.processOpen(url, fromApplication: "")
}
```

Or you can use https://pub.dev/packages/flutter_login_vk and do not change `AppDelegate` at all

**Comment by godzeit** [comment]
I found out it was not whole answer, but anyway thank you. If somebody will strugle please look there [https://github.com/darwin-morocho/flutter-facebook-auth/issues/6#issuecomment-624943909]

**Comment by greymag** [comment]
Glad that you fix the issue! But I must say: adding code that works with `FBSDKCoreKit` in your `AppDelegate` - it's **bad** solution. Yes, it's working, but this not makes it better =)

I would recommend use https://pub.dev/packages/flutter_login_vk for login via VK, that doesn't have such problems.

**Comment by godzeit** [comment]
@greymag can you please explain why it is bad solution?
By the way I did try to use your plugin, but faced a problem while migrating to flutterEmbedding v2. My app started freezing on android release mode on splash screen after migration.

**Comment by greymag** [comment]
Here is my thoughts:
1. You write code in `application(_ app, open url, options)` which already written in plugin and in Facebook SDK implementation. Duplicating code **is bad**.
2. From my point of view plugin shouldn't require changes of `AppDelegate`, if it can be avoided. So if plugin force you to do it - it's **not good**.
3. If something will changes (for example SDK will updated) - you have to change your code, not only update the plugin. It's **unpleasant**.
4. Some implementation in plugin may be rely on call this method (now it's not), so potentially this solution can leads to a bug. That's **dangerous**.

That's why I say that this is a bad solution.

That's only my opinion, and if you fully understand what does code that you write in `AppDelegate` and it's OK for you - go for it! 

**P. S.**

>  faced a problem while migrating to flutterEmbedding v2

That's too bad, but maybe it makes sense to figure it out, because previous embedding is outdated and if it's long term project, you will probably need to migrate anyway eventually.

**Comment by Odaykhazaleh** [comment]
@greymag can you please explain how did manage to login via Facebook app?

**Comment by greymag** [comment]
Hey @Odaykhazaleh. It's the Facebook SDK that decides what to use for login. The plugin does not set the login behaviour, it uses recommended default [NATIVE_WITH_FALLBACK](https://github.com/facebook/facebook-android-sdk/blob/1cffa1132c53e35c7e7dd6d0c2703a5285496e65/facebook-common/src/main/java/com/facebook/login/LoginBehavior.kt#L17):

> Specifies that login should attempt login in using a native app in the Facebook Family of Apps, and if that does not work, fall back to web dialog auth. .
