### ISSUE TITLE
Why we should put FaceBookLogin object in the widget class?

### ISSUE THREAD

**Issue by MeshkaniMohammad** [Innim/flutter_login_facebook#29]
Hi.
I wanted to propagate  `final facebook = FacebookLogin(debug: true,)` with provider but seems we must put it in Widget class of Stateful widget to make it work.
Is there any reason?
Should I do anything to make it work in another place?

**Comment by greymag** [comment]
Hi. You can put in any place you want. It's have just one limitation: if you create instance immediately on app run and you have `debug: true` - make sure you call `WidgetsFlutterBinding.ensureInitialized();`.

That needed because when we have `debug: true` - plugin trying to get FB SDK versions on creation. And this is required native code call, which fails if widget binding is not initialized.

But I would advise to create instance when you need one, and not on app start.

**Comment by MeshkaniMohammad** [comment]
I tried to make it accessible with Provider and don't have logic inside widgets but i got ```no implementation found for sdkVersion``` error.

**Comment by greymag** [comment]
Yes, that's what I wrote about - call `WidgetsFlutterBinding.ensureInitialized();` before it.

Or add facebook login an a lazy dependency in Provider.
