### ISSUE TITLE
No webview in version 0.3.0

### ISSUE THREAD

**Issue by forgetabout** [Innim/flutter_login_facebook#36]
Worked out of the gate until version 0.3.0

Since version 0.3.0, the login process kicks off a device browser (instead of a dialog type webview in previous versions). After successfully logging in, the callbacks to cancel, success or error are not made and a popup is showed in the Chrome browser to leave the page. A black screen is the result.  

Happens on Android device. I have seen other Facebook login packages that force some kind of loginBehavior (webview). 
Curious about your thoughts to get the old behavior back in the new SDK. Thanks in advance. 

I have downgraded for now.

**Comment by greymag** [comment]
Hey! 

Which Android version and device that problem happens? I just try it out on 3 different devices and all works well.

**Comment by forgetabout** [comment]
Android 8.1. I have added a screencast for version 0.3.0 versus the previous version, no changes to anything in the code. Not sure what changed, but it works if I press 'Yes' when the browser asks me to view content in another app. I still prefer the layover behavior from the previous version since the user does not leave the app.

Old behavior (0.2.1): https://ln2.sync.com/dl/45747e080/kqqsyp8x-hq3c8bst-fyq8yxi2-bvvjq5b6
New behavior(0.3.0): https://ln2.sync.com/dl/b9232c010/7n88kmn4-ixukb97z-eipe76ge-99kk9fc3

**Comment by greymag** [comment]
Oh, I see. I had this window too. But I thinks it is a valid behaviour. 

I don't really know why this behaviour changes after upgrade on new FB SDK, because the default `loginBehavior` remained as it was: `LoginBehavior.NATIVE_WITH_FALLBACK`. Looks like it's some internal facebook changes, and I think it's better to put up with it than fight against SDK evolution.

However, I can add settings to set `loginBehavior` and you can try to change it manually (not sure if it helps). Or you can stay on previous version - it's fully workings, only with previous Facebook SDK.

**Comment by forgetabout** [comment]
Hi Greymag,

Thanks for your reply. No need to make any more changes. Just nw I logged in on GitHub Android, exactly same procedure. If they do it that way too, then it should be normal.

Thanks again!
